Add startup command to README.md
gessnerfl/fake-smtp-server pull request #39
Opened 2021-03-05 22:06 UTC by adrianbartnik

Simply change to the `README.md` to make it easy to startup the application for the ones who don't want to directly use the Docker Image.

2021-03-06 17:57 UTC, gessnerfl requested changes
Thanks for your contribution. Can you please change the required Java version. Afterwards I would merge the PR.

2021-03-06 17:57 UTC, gessnerfl commented on README.md
> +You need Java 8 installed. In order to run this application locally, execute:
fakesmtp server requires Java 11

2021-03-06 22:23 UTC, adrianbartnik commented on README.md
> +You need Java 8 installed. In order to run this application locally, execute:
Make sense. Changed it accordingly.

2021-03-07 11:47 UTC, gessnerfl approved these changes

2021-03-07 11:48 UTC, merged